# docker-compose.yml

version: '3.8'
services:
  backend:
    container_name: backend
    build: backend
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
  
  frontend:
    container_name: frontend
    build: frontend
    restart: always
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network

  postgres:
    container_name: postgres
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - app-network
      

volumes:
  postgres:

networks:
  app-network:
    driver: bridge
